"""Initial migration - create all tables

Revision ID: 96b8963bd01b
Revises: 
Create Date: 2025-12-01 01:41:01.444238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b8963bd01b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('loans', sa.Column('payment_day', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('payment_frequency', sa.String(length=50), nullable=False))
    op.add_column('loans', sa.Column('origination_fee', sa.Numeric(precision=19, scale=2), nullable=False))
    op.add_column('loans', sa.Column('insurance_monthly', sa.Numeric(precision=19, scale=2), nullable=False))
    op.add_column('loans', sa.Column('rate_type', sa.String(length=50), nullable=False))
    op.add_column('loans', sa.Column('interest_calculation_method', sa.String(length=50), nullable=False))
    op.add_column('loans', sa.Column('grace_period_months', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('late_payment_penalty_rate', sa.Numeric(precision=8, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'late_payment_penalty_rate')
    op.drop_column('loans', 'grace_period_months')
    op.drop_column('loans', 'interest_calculation_method')
    op.drop_column('loans', 'rate_type')
    op.drop_column('loans', 'insurance_monthly')
    op.drop_column('loans', 'origination_fee')
    op.drop_column('loans', 'payment_frequency')
    op.drop_column('loans', 'payment_day')
    op.drop_column('loans', 'start_date')
    # ### end Alembic commands ###
