"""Initial tables

Revision ID: b7ee9d13c3af
Revises: 
Create Date: 2025-12-01 01:53:09.183120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ee9d13c3af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=19, scale=2), nullable=True),
    sa.Column('principal', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('payment_frequency', sa.String(length=50), nullable=False),
    sa.Column('origination_fee', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('insurance_monthly', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('interest_calculation_method', sa.String(length=50), nullable=False),
    sa.Column('grace_period_months', sa.Integer(), nullable=False),
    sa.Column('late_payment_penalty_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('amortization_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('scheduled_payment', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('scheduled_principal', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('scheduled_interest', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('insurance_amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_grace_period', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amortization_schedule_id'), 'amortization_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_amortization_schedule_loan_id'), 'amortization_schedule', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amortization_schedule_loan_id'), table_name='amortization_schedule')
    op.drop_index(op.f('ix_amortization_schedule_id'), table_name='amortization_schedule')
    op.drop_table('amortization_schedule')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
